# Used settings
recurrency: 0.0
static_node_size: 40
weights: False
input_start: -1.0
node_inputs: 2
# Evolutionary settings
mutate_method: ":gene_mutate"
crossover_method: ":single_point_crossover"
starting_nodes: 25
node_size_cap: 75
save_best: True
# Unused settings
total_evals: 50000
# Mutation
active_mutate: False
input_mutation_rate: 0.2
output_mutation_rate: 0.3
node_mutation_rate: 0.1
node_size_delta: 0.0
modify_mutation_rate: 0.0
# Oneplus settings
lambda: 3
