const global MORPHOGEN_REMAINDER = 1.0
const global STEP_INIT = 100
const global STEP_TOTAL = 2000
const global CHANGE_STOP = 0.2
const global AXON_MAX = 20
const global MIN_DIST = 0.01
const global N_MORPHS = 4
const global N_PARAMS = 4
const global N_CTYPES = 4
const global N_NSC = 20
const global DIMS = [5, 5, 5]
const global N_D = 3
